name: python test actions demo
on: 
  workflow_dispatch:
  push:
    paths:
      - 'python-demo/**'
      - '.github/workflows/python-demo.yml'

jobs:
    build_and_test:
        runs-on: ubuntu-latest
        steps:
            - name: pre - checkout
              run: | 
                 echo Hello World
                 pwd
                 ls -lH
                 echo ${{ github.repositoryUrl }}

            - name: checkout 
              uses: actions/checkout@v6

            - name:  after checkout
              run: | 
                ls -lH
                date
            
            - name: run test 
              run: |
                pip install pytest
                pytest