name: python-sha256 training with upload-artifacts
on:
  workflow_dispatch: 
  push:
    paths:
      - 'python-sha256/**'
      - '.github/workflows/python-sha256.yml'

jobs:
  build_on_windows:
    runs-on: windows-latest
    steps:
      - name: build on windows
        run: echo Hellow Windows 

      - name: checkout
        uses: actions/checkout@v6

      - name: install pyinstaller
        run: pip install pyinstaller
      
      - name: build pyinstaller 
        working-directory: python-sha256
        run: |
          pyinstaller sha256.py -F

      - name: upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: windows-sha256.exe
          path: python-sha256/dist/sha256.exe

  build_on_linux:
    runs-on: ubuntu-latest
    steps:
      - name: build on windows
        run: echo Hellow Windows 

      - name: checkout
        uses: actions/checkout@v6

      - name: install pyinstaller
        run: pip install pyinstaller
      
      - name: build pyinstaller 
        working-directory: python-sha256
        run: |
          pyinstaller sha256.py -F

      - name: upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: liunux-sha256
          path: python-sha256/dist/sha256

  build_on_mac:
    runs-on: macos-latest
    steps:
      - name: build on windows
        run: echo Hellow Windows 

      - name: checkout
        uses: actions/checkout@v6

      - name: install pyinstaller
        run: pip install pyinstaller
      
      - name: build pyinstaller 
        working-directory: python-sha256
        run: |
          pyinstaller sha256.py -F

      - name: upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: macos-sha256
          path: python-sha256/dist/sha256