on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    job1:
        runs-on: ubuntu-22.04
        steps:
            - name: テストname
              run: pwd

            - name: テストstep2
              run: ls